In [34]:
import sklearn.datasets
import numpy as np

In [35]:
cancer_ds = sklearn.datasets.load_breast_cancer()

In [36]:
#Lets organize X and Y
X = cancer_ds.data
Y = cancer_ds.target

In [38]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [9]:
#About no. of rows and columns
print(X.shape, Y.shape)

(569, 30) (569,)


In [10]:
#Get data in dataframe
import pandas as pd
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds.feature_names)
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [11]:
#Rename the target variable
data['class'] = cancer_ds.target

In [12]:
#investigate
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [13]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [14]:
#How many Malignant and Benign
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [15]:
print(cancer_ds.target_names)

['malignant' 'benign']


In [16]:
data.groupby('class').mean()

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

In [17]:
#Train Test SPLIT

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X = data.drop('class', axis = 1)
Y = data['class']

In [20]:
type(X)

pandas.core.frame.DataFrame

In [21]:
#Magical line of code to split a datasets
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

In [22]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (426,) (143,)


In [23]:
#END 17-Feb-2021

In [24]:
print(X_train.mean(),X_test.mean(),X.mean())

mean radius                 14.366103
mean texture                19.524319
mean perimeter              93.694155
mean area                  678.077230
mean smoothness              0.097151
mean compactness             0.108817
mean concavity               0.094558
mean concave points          0.052372
mean symmetry                0.182661
mean fractal dimension       0.062943
radius error                 0.421461
texture error                1.230138
perimeter error              2.998626
area error                  42.498707
smoothness error             0.007024
compactness error            0.026434
concavity error              0.032553
concave points error         0.012237
symmetry error               0.020806
fractal dimension error      0.003793
worst radius                16.603094
worst texture               26.030023
worst perimeter            109.702465
worst area                 917.192019
worst smoothness             0.133329
worst compactness            0.265646
worst concav

In [25]:
#Binarised Input
X_binarised_train = X_train.apply(pd.cut,bins=2,labels=[1,0])#try[0,1]

In [26]:
X_binarised_train.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
336           1            1              1         1               1   
165           1            1              1         1               1   
132           1            1              1         1               1   
58            1            1              1         1               1   
271           1            1              1         1               1   

    mean compactness mean concavity mean concave points mean symmetry  \
336                1              1                   1             1   
165                1              1                   1             1   
132                1              1                   1             0   
58                 1              1                   1             1   
271                1              1                   1             1   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
336                      1  ...            1             1               1   
165                      1  ...            1             1               1   
132                      1  ...            1             0               1   
58                       1  ...            1             1               1   
271                      1  ...            1             1               1   

    worst area worst smoothness worst compactness worst concavity  \
336          1                1                 1               1   
165          1                1                 1               1   
132          1                1                 1               1   
58           1                1                 1               1   
271          1                1                 1               1   

    worst concave points worst symmetry worst fractal dimension  
336                    1              1                       1  
165                    1              1                       1  
132                    1              1                       1  
58                     1              1                       1  
271                    1              1                       1  

[5 rows x 30 columns]

In [27]:
#Binarised Input
X_binarised_test = X_test.apply(pd.cut,bins=2,labels=[1,0])#try[0,1]

In [28]:
X_binarised_test.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
152           1            1              1         1               0   
535           0            1              0         1               0   
59            1            1              1         1               0   
390           1            1              1         1               0   
53            0            1              0         1               0   

    mean compactness mean concavity mean concave points mean symmetry  \
152                0              0                   1             0   
535                0              0                   0             0   
59                 1              1                   1             1   
390                1              1                   1             1   
53                 0              1                   0             0   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
152                      0  ...            1             1               1   
535                      1  ...            0             1               0   
59                       1  ...            1             1               1   
390                      1  ...            1             1               1   
53                       1  ...            1             1               1   

    worst area worst smoothness worst compactness worst concavity  \
152          1                1                 1               0   
535          1                1                 1               0   
59           1                0                 1               1   
390          1                0                 1               1   
53           1                1                 1               1   

    worst concave points worst symmetry worst fractal dimension  
152                    0              1                       0  
535                    0              1                       1  
59                     1              1                       1  
390                    1              1                       1  
53                     1              1                       1  

[5 rows x 30 columns]

In [29]:
#Binarised Input - trying with [0,1]
X_binarised_train = X_train.apply(pd.cut,bins=2,labels=[0,1])
X_binarised_train.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
336           0            0              0         0               0   
165           0            0              0         0               0   
132           0            0              0         0               0   
58            0            0              0         0               0   
271           0            0              0         0               0   

    mean compactness mean concavity mean concave points mean symmetry  \
336                0              0                   0             0   
165                0              0                   0             0   
132                0              0                   0             1   
58                 0              0                   0             0   
271                0              0                   0             0   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
336                      0  ...            0             0               0   
165                      0  ...            0             0               0   
132                      0  ...            0             1               0   
58                       0  ...            0             0               0   
271                      0  ...            0             0               0   

    worst area worst smoothness worst compactness worst concavity  \
336          0                0                 0               0   
165          0                0                 0               0   
132          0                0                 0               0   
58           0                0                 0               0   
271          0                0                 0               0   

    worst concave points worst symmetry worst fractal dimension  
336                    0              0                       0  
165                    0              0                       0  
132                    0              0                       0  
58                     0              0                       0  
271                    0              0                       0  

[5 rows x 30 columns]

In [48]:
#Binarised Input - trying with [0,1]
X_binarised_test = X_test.apply(pd.cut,bins=2,labels=[0,1])
X_binarised_test.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
152           0            0              0         0               1   
535           1            0              1         0               1   
59            0            0              0         0               1   
390           0            0              0         0               1   
53            1            0              1         0               1   

    mean compactness mean concavity mean concave points mean symmetry  \
152                1              1                   0             1   
535                1              1                   1             1   
59                 0              0                   0             0   
390                0              0                   0             0   
53                 1              0                   1             1   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
152                      1  ...            0             0               0   
535                      0  ...            1             0               1   
59                       0  ...            0             0               0   
390                      0  ...            0             0               0   
53                       0  ...            0             0               0   

    worst area worst smoothness worst compactness worst concavity  \
152          0                0                 0               1   
535          0                0                 0               1   
59           0                1                 0               0   
390          0                1                 0               0   
53           0                0                 0               0   

    worst concave points worst symmetry worst fractal dimension  
152                    1              0                       1  
535                    1              0                       0  
59                     0              0                       0  
390                    0              0                       0  
53                     0              0                       0  

[5 rows x 30 columns]

In [49]:
#type of X_binarised_test
type(X_binarised_test)

pandas.core.frame.DataFrame

In [52]:
#Convert to arrays
#X_binarised_train = X_binarised_train.values
#X_binarised_test = X_binarised_test.values

In [65]:
import random
#ML Model
b=10 #What are the possible values that b can take?


i=random.randint(0,X_train.shape[0])
print (i)
if(np.sum(X_binarised_train[i,:])>=b):
    print('ML Model says its Malignant')
else:
    print('ML Model says its Benign')
    
if(Y_train[i]==1):
    print('Actual Output is Malignant')
else:
    print('Actual Output is Benign')
    
#accuracy?

137
ML Model says its Benign
Actual Output is Malignant


In [68]:
#Accuracy 
def get_predictions(X_binarised_train, Y_train,b):
    pred=[]
    for i in range(X_binarised_train.shape[0]):
        if (np.sum(X_binarised_train.shape[0])):
            pred.append(1)
        else:
            pred.append(0)
    df=pd.DataFrame(columns=['predictions','True_values'])
    df['predictions']=pred
    df['True_values']=Y_train
    df['cor_wr']=df['predictions']==df['True_values']
    display(df['cor_wr'].value_counts())
    return df['cor_wr'].value_counts()[1] / (df['cor_wr'].value_counts())

In [71]:
#Calculating Accuracy
no=X_train.shape[1]
for b in range(no):
    print('value of b:', b)
    x=get_predictions(X_binarised_train, Y_train, b)
    print('accuracy: ',x)

value of b: 0


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 1


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 2


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 3


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 4


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 5


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 6


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 7


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 8


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 9


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 10


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 11


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 12


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 13


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 14


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 15


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 16


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 17


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 18


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 19


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 20


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 21


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 22


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 23


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 24


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 25


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 26


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 27


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 28


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
value of b: 29


False    252
True     174
Name: cor_wr, dtype: int64

accuracy:  False    0.690476
True     1.000000
Name: cor_wr, dtype: float64
